Repository diptanshumahish/watch, pull requests merged in 2023-03, with the labels that each got.

#31 Solves Full screen page for the movie details #28 under JWOC
  screen_ui_designs/sagnik-sanyal-movie_page1.png
  screen_ui_designs/sagnik-sanyal-movie_page2.png
Labels: JWOC, Medium, design ui/ux

#32 Updated the readme , documentation
  CONTRIBUTING.md
  README.md
Labels: JWOC, easy, no code

#36 Solves issue #34 under JWOC
  lib/main.dart
  lib/screens/homepage.dart
  lib/screens/mainscreenpages/profile.dart
  lib/screens/profile/profile.dart
  lib/shared/background_painter.dart
Labels: Flutter, JWOC, Hard

#37 Added CODE_OF_CONDUCT and LICENSE
  CODE_OF_CONDUCT.md
  LICENSE.md
Labels: JWOC, easy, no code

#38 Solves issue Full screen page to be coded #35 under JWOC
  lib/screens/homepage.dart
  lib/screens/movie_details/actors_tile.dart
  lib/screens/movie_details/movie_details_screen.dart
  lib/shared/background_painter.dart
  lib/shared/custom_paints.dart
  pubspec.yaml
Labels: Flutter, JWOC, Hard

#39 Design of the particular categories page #18
  screen_ui_designs/sagnik-sanyal-categories.png
Labels: Flutter, JWOC, Hard

#42 riverpod migration #40
  .gitignore
  lib/main.dart
  lib/providers/disposable_provider/disposable_provider.dart
  lib/providers/multi_provider.dart
  lib/providers/theme_provider.dart
  lib/providers/user_provider.dart
  lib/screens/movie_details/movie_details_screen.dart
  lib/services/auth_service.dart
  lib/services/service_locator.dart
  lib/services/shared_preference_service.dart
  pubspec.lock
  pubspec.yaml
Labels: Flutter, JWOC, Hard

#47 set and get user choices from Firestore #45 under JWOC
  lib/app/errors/errors.dart
  lib/app/errors/failure.dart
  lib/app/errors/failure_ext.dart
  lib/app/errors/type_defs.dart
  lib/app/theme/app_theme.dart
  lib/app/utils/snackbar/snackbar.dart
  lib/main.dart
  lib/src/features/authentication/data/auth_api.dart
  lib/src/features/authentication/data/auth_api_impl.dart
  lib/src/models/user_model.dart
  lib/src/models/user_model.freezed.dart
  lib/src/models/user_model.g.dart
  lib/src/providers/firestore_provider.dart
  lib/src/providers/user_provider.dart
  pubspec.lock
  pubspec.yaml
Labels: Flutter, JWOC, Hard

#48 Load movies on the basis of genre like thriller and horror as it was present in prevoius homepage from tmdb
  lib/app/constants/api_urls.dart
  lib/app/constants/constants.dart
  lib/app/constants/enums.dart
  lib/app/errors/failure_ext.dart
  lib/src/features/home/data/tmdb_api.dart
  lib/src/features/home/presentation/home_view/components/home.dart
  lib/src/features/home/presentation/home_view/home_screen.dart
  lib/src/models/all_genres_model.dart
  lib/src/models/genres_model.dart
  lib/src/models/genres_model.freezed.dart
  lib/src/models/genres_model.g.dart
  lib/src/providers/global_providers.dart
  lib/src/providers/http_base_provider.dart
  pubspec.lock
  pubspec.yaml
Labels: Flutter, JWOC, Hard

#49 TmDB API Integration (ii) #46 under JWOC
  lib/src/features/home/data/tmdb_api.dart
  lib/src/features/home/presentation/home_view/components/home.dart
  lib/src/features/home/presentation/home_view/home_screen.dart
  lib/src/features/home/presentation/movie_details/actors_tile.dart
  lib/src/features/home/presentation/movie_details/movie_details_screen.dart
  lib/src/models/cast_model.dart
  lib/src/models/cast_model.freezed.dart
  lib/src/models/cast_model.g.dart
  lib/src/models/genres_model.dart
  lib/src/models/genres_model.freezed.dart
  lib/src/models/genres_model.g.dart
  pubspec.lock
  pubspec.yaml
Labels: Flutter, JWOC, Hard

#51 Movies/ web series search #50 JWOC
  lib/app/constants/api_urls.dart
  lib/src/features/home/app/controller/search_controller.dart
  lib/src/features/home/app/state/search_state.dart
  lib/src/features/home/app/state/search_state.freezed.dart
  lib/src/features/home/data/tmdb_api.dart
  lib/src/features/home/presentation/explore_screen/components/search_result_widget.dart
  lib/src/features/home/presentation/explore_screen/explore.dart
  lib/src/features/home/presentation/home_view/components/explore.dart
  lib/src/features/home/presentation/home_view/components/home.dart
  lib/src/features/home/presentation/home_view/home_screen.dart
  lib/src/features/home/presentation/movie_details/movie_details_screen.dart
  lib/src/models/all_genres_model.dart
  lib/src/models/genres_model.dart
  lib/src/models/genres_model.freezed.dart
  lib/src/models/genres_model.g.dart
Labels: Flutter, JWOC, Hard

#54 Issue with Hero transition in homepage under JWOC #52 fixed under JWOC
  lib/src/features/home/presentation/home_view/components/home.dart
  lib/src/features/home/presentation/movie_details/movie_details_screen.dart
  lib/src/shared/custom_hero.dart
Labels: Flutter, JWOC, Medium

#56 Firebase auth , with email password #53 solved under JWOC
  lib/app/errors/failure_ext.dart
  lib/app/utils/snackbar/show_info_snackbar.dart
  lib/app/utils/snackbar/snackbar_ext.dart
  lib/app/utils/textfield_validators.dart
  lib/src/app.dart
  lib/src/features/authentication/app/controller/signup_controller.dart
  lib/src/features/authentication/app/state/signup_state.dart
  lib/src/features/authentication/controller/auth_controller.dart
  lib/src/features/authentication/data/auth_api.dart
  lib/src/features/authentication/data/auth_api_impl.dart
  lib/src/features/authentication/presentation/login/login_screen.dart
  lib/src/features/authentication/presentation/signup/signup_screen.dart
  lib/src/features/splash/presentation/splash_screen.dart
  lib/src/providers/firestore_provider.dart
  lib/src/providers/user_provider.dart
  lib/src/shared/loading_dialog.dart
  pubspec.lock
  pubspec.yaml
Labels: Flutter, JWOC, Medium

#58 Add movies / web series to liked items array #57
  lib/src/features/home/app/controller/favourites_controller.dart
  lib/src/features/home/app/controller/search_controller.dart
  lib/src/features/home/app/state/favourite_state.dart
  lib/src/features/home/app/state/favourite_state.freezed.dart
  lib/src/features/home/app/state/search_state.dart
  lib/src/features/home/data/tmdb_api.dart
  lib/src/features/home/presentation/favourites/favourites_screen.dart
  lib/src/features/home/presentation/home_view/components/fav.dart
  lib/src/features/home/presentation/home_view/components/home.dart
  lib/src/features/home/presentation/home_view/home_screen.dart
  lib/src/features/home/presentation/movie_details/movie_details_screen.dart
  lib/src/models/movie_details_model.dart
  lib/src/models/movie_details_model.freezed.dart
  lib/src/models/movie_details_model.g.dart
  lib/src/models/user_model.dart
  lib/src/models/user_model.freezed.dart
  lib/src/models/user_model.g.dart
  lib/src/providers/firestore_provider.dart
  lib/src/providers/global_providers.dart
  lib/src/providers/user_provider.dart
Labels: Flutter, JWOC, Hard

#62 Fix routes globally and remove splash screen dependency #61
  lib/main.dart
  lib/src/app.dart
  lib/src/features/authentication/presentation/login/login_screen.dart
  lib/src/features/authentication/presentation/signup/signup_screen.dart
  lib/src/features/home/app/controller/favourites_controller.dart
  lib/src/features/home/presentation/movie_details/movie_details_screen.dart
  lib/src/features/splash/presentation/splash_screen.dart
  lib/src/features/splash/splash_screen.dart
  lib/src/providers/global_providers.dart
  lib/src/routes/app_routes.dart
  lib/src/routes/router.dart
  pubspec.lock
  pubspec.yaml
Labels: Flutter, JWOC, Hard

#63 Firebase login with email password #55 under JWOC
  lib/src/features/authentication/app/controller/login_controller.dart
  lib/src/features/authentication/app/state/login_state.dart
  lib/src/features/authentication/data/auth_api.dart
  lib/src/features/authentication/data/auth_api_impl.dart
  lib/src/features/authentication/presentation/login/login_screen.dart
  lib/src/features/authentication/presentation/signup/signup_screen.dart
  lib/src/routes/router.dart
Labels: Flutter, JWOC, Medium

#65 Add Provider Observer globally with proper logging #64 solved under JWOC
  lib/main.dart
  lib/src/features/authentication/data/auth_api.dart
  lib/src/features/home/app/controller/favourites_controller.dart
  lib/src/features/home/app/controller/search_controller.dart
  lib/src/features/home/data/tmdb_api.dart
  lib/src/providers/firestore_provider.dart
  lib/src/providers/global_providers.dart
  lib/src/providers/http_base_provider.dart
  lib/src/providers/local_storage_provider.dart
  lib/src/providers/provider_observer.dart
  lib/src/providers/theme_provider.dart
  lib/src/providers/user_provider.dart
  pubspec.lock
  pubspec.yaml
Labels: Flutter, JWOC, Hard

#67 Show customised message , name of currently logged in user
  lib/src/features/home/app/controller/favourites_controller.dart
  lib/src/features/home/presentation/explore_screen/components/search_result_widget.dart
  lib/src/features/home/presentation/explore_screen/explore.dart
  lib/src/features/home/presentation/favourites/favourites_screen.dart
  lib/src/features/home/presentation/home_view/components/home.dart
  lib/src/features/home/presentation/profile/profile.dart
  lib/src/providers/firestore_provider.dart
Labels: Flutter, JWOC, Hard

#69 Shimmer loaders
  lib/main.dart
  lib/src/features/home/app/controller/favourites_controller.dart
  lib/src/features/home/app/controller/search_controller.dart
  lib/src/features/home/presentation/explore_screen/components/search_result_widget.dart
  lib/src/features/home/presentation/explore_screen/explore.dart
  lib/src/features/home/presentation/favourites/favourites_screen.dart
  lib/src/shared/shimmer_loaders.dart
Labels: Flutter, JWOC, Medium

#71 Network Checker using riverpod under JWOC
  lib/app/constants/enums.dart
  lib/src/providers/network_checker_provider.dart
  lib/src/shared/network_checker.dart
Labels: Flutter, JWOC, Medium

#73 google fonts added with text theming
  lib/app/theme/app_theme.dart
  lib/main.dart
  lib/src/app.dart
  lib/src/features/authentication/presentation/signup/signup_screen.dart
  lib/src/features/home/presentation/explore_screen/explore.dart
  lib/src/features/home/presentation/favourites/favourites_screen.dart
  lib/src/features/home/presentation/home_view/components/home.dart
  lib/src/features/home/presentation/movie_details/actors_tile.dart
  lib/src/features/home/presentation/movie_details/movie_details_screen.dart
  lib/src/features/home/presentation/profile/profile.dart
  pubspec.lock
  pubspec.yaml
Labels: Flutter, JWOC, Medium

#79 Firebase forgot password service using riverpod #78
  .gitignore
  lib/main.dart
  lib/src/features/authentication/app/controller/forgot_password_controller.dart
  lib/src/features/authentication/app/state/forgot_password_state.dart
  lib/src/features/authentication/data/auth_api.dart
  lib/src/features/authentication/data/auth_api_impl.dart
  lib/src/features/authentication/presentation/forgot_password/forgot_password_screen.dart
  lib/src/features/authentication/presentation/login/login_screen.dart
  lib/src/routes/router.dart
Labels: Flutter, JWOC, Hard

#81 Pinput field to autocatch OTP is mobile field is reset
  lib/src/features/authentication/app/controller/forgot_password_controller.dart
  lib/src/features/authentication/app/state/forgot_password_state.dart
  lib/src/features/authentication/presentation/forgot_password/forgot_password_screen.dart
  pubspec.lock
  pubspec.yaml
Labels: Flutter, JWOC, Hard

#83 Logout user and clear any sort of data in local storage or provider #82
  lib/src/features/authentication/data/auth_api.dart
  lib/src/features/authentication/data/auth_api_impl.dart
  lib/src/features/authentication/presentation/signup/signup_screen.dart
  lib/src/features/home/app/controller/logout_controller.dart
  lib/src/features/home/presentation/explore_screen/components/search_result_widget.dart
  lib/src/features/home/presentation/explore_screen/explore.dart
  lib/src/features/home/presentation/favourites/favourites_screen.dart
  lib/src/features/home/presentation/home_view/components/fulldetails.dart
  lib/src/features/home/presentation/home_view/components/home.dart
  lib/src/features/home/presentation/home_view/home_screen.dart
  lib/src/features/home/presentation/movie_details/actors_tile.dart
  lib/src/features/home/presentation/movie_details/movie_details_screen.dart
  lib/src/features/home/presentation/profile/components/logout_dialog.dart
  lib/src/features/home/presentation/profile/profile.dart
  lib/src/features/home/presentation/reccomendations.dart
  lib/src/features/home/presentation/trending/trending_movies_screen.dart
Labels: Flutter, JWOC, Medium

#85 Allow Google login functionality #84
  lib/src/features/authentication/app/controller/login_controller.dart
  lib/src/features/authentication/data/auth_api.dart
  lib/src/features/authentication/data/auth_api_impl.dart
  lib/src/features/authentication/presentation/login/login_screen.dart
Labels: Flutter, JWOC, Medium

#87 Show movie details from the grid of trending movies using TMDB #86
  lib/src/features/authentication/app/controller/login_controller.dart
  lib/src/features/home/data/tmdb_api.dart
  lib/src/features/home/presentation/trending/trending_movies_screen.dart
Labels: Flutter, JWOC, Hard

#89 Upload profile image to firebase storage #88
  analysis_options.yaml
  android/app/src/main/AndroidManifest.xml
  lib/main.dart
  lib/src/app.dart
  lib/src/features/authentication/app/controller/forgot_password_controller.dart
  lib/src/features/authentication/app/controller/login_controller.dart
  lib/src/features/authentication/app/controller/signup_controller.dart
  lib/src/features/authentication/app/state/forgot_password_state.dart
  lib/src/features/authentication/app/state/login_state.dart
  lib/src/features/authentication/app/state/signup_state.dart
  lib/src/features/authentication/data/auth_api.dart
  lib/src/features/authentication/presentation/forgot_password/forgot_password_screen.dart
  lib/src/features/authentication/presentation/login/login_screen.dart
  lib/src/features/authentication/presentation/signup/signup_screen.dart
  lib/src/features/home/app/controller/favourites_controller.dart
  lib/src/features/home/app/controller/logout_controller.dart
  lib/src/features/home/app/controller/profile_controller.dart
  lib/src/features/home/app/controller/search_controller.dart
  lib/src/features/home/app/controller/trending_controller.dart
  lib/src/features/home/data/tmdb_api.dart
  lib/src/features/home/presentation/explore_screen/components/search_result_widget.dart
  lib/src/features/home/presentation/explore_screen/explore.dart
  lib/src/features/home/presentation/favourites/favourites_screen.dart
  lib/src/features/home/presentation/home_view/components/fulldetails.dart
  lib/src/features/home/presentation/home_view/home_screen.dart
  lib/src/features/home/presentation/profile/profile.dart
  lib/src/models/all_genres_model.dart
  lib/src/providers/firebase_storage_provider.dart
  lib/src/providers/firestore_provider.dart
  lib/src/providers/global_providers.dart
  lib/src/providers/http_base_provider.dart
  lib/src/providers/local_storage_provider.dart
  lib/src/providers/network_checker_provider.dart
  lib/src/providers/theme_provider.dart
  lib/src/providers/user_provider.dart
  lib/src/routes/router.dart
  lib/src/shared/custom_paints.dart
  lib/src/shared/network_checker.dart
  lib/src/shared/shimmer_loaders.dart
  pubspec.lock
  pubspec.yaml
Labels: Flutter, JWOC, Hard
